Adding a `pscheduler metrics` command for stats
perfsonar/pscheduler pull request #1070
Opened 2020-09-11 15:49 UTC by tonin

Outputs all the statistics available through the API.  It has 2 output format: json (default) and
prometheus to be used with prometheus-node-exporter textfile exporter.

2020-09-14 13:55 UTC, tonin commented
Output of this new `metrics` command is for JSON:
```
$ pscheduler metrics | jq
{
  "http-queue": {
    "length": 0,
    "backlog": 0
  },
  "paused": {
    "is_paused": false
  },
  "runs": {
    "missed": 0,
    "running": 2406,
    "cleanup": 36,
    "preempted": 0,
    "overdue": 0,
    "failed": 201,
    "pending": 13,
    "nonstart": 3262,
    "finished": 56207,
    "on-deck": 2
  },
  "archiving": {
    "upcoming": 0,
    "backlog": 1
  }
}
```

and for Prometheus:
```
$ pscheduler metrics --format prometheus
# HELP perfsonar_pscheduler_archiving pScheduler archiving queue
# TYPE perfsonar_pscheduler_archiving gauge
perfsonar_pscheduler_archiving{state="upcoming"} 0
perfsonar_pscheduler_archiving{state="backlog"} 1
# HELP perfsonar_pscheduler_paused pScheduler is paused
# TYPE perfsonar_pscheduler_paused gauge
perfsonar_pscheduler_paused{state="is_paused"} 0
# HELP perfsonar_pscheduler_runs Number of pScheduler runs in the different states
# TYPE perfsonar_pscheduler_runs gauge
perfsonar_pscheduler_runs{state="failed"} 201
perfsonar_pscheduler_runs{state="cleanup"} 36
perfsonar_pscheduler_runs{state="nonstart"} 3262
perfsonar_pscheduler_runs{state="finished"} 56207
perfsonar_pscheduler_runs{state="overdue"} 0
perfsonar_pscheduler_runs{state="pending"} 13
perfsonar_pscheduler_runs{state="on-deck"} 2
perfsonar_pscheduler_runs{state="preempted"} 0
perfsonar_pscheduler_runs{state="running"} 2406
perfsonar_pscheduler_runs{state="missed"} 0
# HELP perfsonar_pscheduler_http_queue pScheduler HTTP queue
# TYPE perfsonar_pscheduler_http_queue gauge
perfsonar_pscheduler_http_queue{state="backlog"} 0
perfsonar_pscheduler_http_queue{state="length"} 0
```

2020-09-14 20:57 UTC, mfeit-internet2 requested changes
Just a bunch of small stuff in the comments.  Otherwise appears to work as advertised.

2020-09-14 20:57 UTC, mfeit-internet2 commented on pscheduler-core/pscheduler-core/metrics
> +#!/usr/bin/python3
Program needs to be added to the `COMMANDS` list in the `Makefile`.

2020-09-14 20:57 UTC, mfeit-internet2 commented on pscheduler-core/pscheduler-core/metrics
> +
I recommend adding a `--host` option (see other programs, like `plot-schedule`) and using it in forming URLs for the API.  See comment below.

2020-09-14 20:57 UTC, mfeit-internet2 commented on pscheduler-core/pscheduler-core/metrics
> +        url = pscheduler.api_url("localhost", v["url"] + state)
Use the value of the `host` option here.  If the default for that is `None`, `api_url()` will construct a URL for the local host if the option is not specified.    (FYI, There's an `api_local_host` call in the library.)

2020-09-14 20:57 UTC, mfeit-internet2 commented on pscheduler-core/pscheduler-core/metrics
> +    output = json.dumps(all_stats)
If you want to dump JSON, declare success and exit, call `pscheduler.success_json(all_stats)` for a one-stop solution.

There's also a `json_dump` in the library.

2020-09-14 20:57 UTC, mfeit-internet2 commented on pscheduler-core/pscheduler-core/metrics
> +    output = "Unknown output format"
Call `pscheduler.fail("Error Message")` here.  The error will go to stderr and the program will exit 1.

2020-09-14 20:57 UTC, mfeit-internet2 commented on pscheduler-core/pscheduler-core/metrics
> +print(output)
Call `pscheduler.succeed(output)` here to exit cleanly.

2020-09-15 16:14 UTC, tonin commented
Thanks for your review Mark.  I made the changes, let me know if you want anything else.

2020-09-15 17:18 UTC, mfeit-internet2 approved these changes
Looks good.  I'll pull it and delete the branch.

2020-09-15 17:18 UTC, merged